#!/usr/bin/env bash

set -efu

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"

  cd "$shome"
  mkdir -p "$shome/bin"

  block compile pipenv
  ln -nfs $(pipenv run which eb ebp) "$shome/bin/"
}

main "$@"
