#!/usr/bin/env bash

set -efu

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"

  block compile virtualenv
  mkdir -p "$shome/bin"
  ln -nfs ../vendor/virtualenv/bin/{eb,ebp} "$shome/bin/"
}

main "$@"
