#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_eb="$(eb --version 2>&1 | awk '{print $3}' || true)"
  jq -n --arg eb "$ver_eb" '{eb: $eb}'
}

version "$@"
