#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_eb="0.0.1"
  jq -n --arg eb "$ver_eb" '{eb: $eb}'
}

version "$@"
